#! configuration/base.yaml
application:
  port: 8000
  hmac_secret: "silly-secret-string-that-is-very-long-ishi-silly-secret-string-that-is-very-long-ish"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  sender_email: "kevin@turing.club"
  base_url: "localhost"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000

redis_uri: "redis://127.0.0.1:6379"
